security:
    oauth2:
        resource:
            jwt:
                
                key-uri: "http://localhost:8081/auth/oauth/token_key"
security.user.password: geheim
security.user.name: eicke
server.context-path: /travelExpenseManager 
logging.level.org.springframework: INFO
test.value: true
server.port: 9030
---
spring:
  profiles: development

  data:
    mongodb:
      database: meineDatenbankExpenses
---
spring:
  profiles: test

  data:
    mongodb:
      database: testDBExpenses
  
---
spring:
  profiles: openshift

  data:
    mongodb:
      uri: ${MONGO_URL}
      database: meineProdDBExpenses
      
  